version: "3.8"

services:
  content:
    image: ghost:3.36.0
    volumes:
      # - jcdbprod-ghost:/var/lib/ghost/content
      - ${CONTENT_VOLUME}:/var/lib/ghost/content
    ports:
      - ${PORT}:2368
    networks:
      - public
    deploy:
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        # max_attempts: 3
        window: 120s
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
        max_replicas_per_node: 1
    env_file:
      - .env
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: ${DATABASE_CLIENT}
      database__connection__host: ${DATABASE_HOST}
      database__connection__user: ${DATABASE_USER}
      database__connection__password: ${DATABASE_PASSWORD}
      database__connection__database: ${DATABASE_NAME}
      # for the newsletter
      mail__transport: SMTP
      mail__options__service: ${MAIL_OPTIONS_SERVICE}
      mail__options__host: ${MAIL_OPTIONS_HOST}
      mail__options__auth__user: ${MAIL_OPTIONS_USER}
      mail__options__auth__pass: ${MAIL_OPTIONS_PASS}
      # avoid econn reset
      database__pool__min: 0
      url: ${WEBSITE_URL}
# deprecated below
#    depends_on:
#      - ghostdb

  ghostdb:
    image: tobi312/rpi-mariadb:10.3
    networks:
      - public
    deploy:
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints: [node.role == manager]
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql

networks:
  public:
#    driver: overlay
    external: true
#    attachable: true
